branches:
  only:
  - master

language: objective-c
osx_image: xcode9.1

script:
- xcodebuild -project MediaKeyEnabler.xcodeproj -scheme "MediaKeyEnabler" build

after_success:
- bash <(curl -s https://codecov.io/bash)  -J 'MediaKeyEnabler'
